server:
  port: 8082

spring:
  application:
    name: payment-service
  profiles:
    active: local

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
rmpt:
  kafka:
    topic:
      orders: orders.events