spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/rmpt
    username: rmpt
    password: rmpt

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
rmpt:
  kafka:
    topic:
      orders: orders.events
logging:
  level:
    com.zaxxer.hikari: TRACE
    org.hibernate.engine.jdbc.env.internal: DEBUG
    org.springframework.jdbc.datasource: DEBUG


