server:
  port: 8081

spring:
  application:
    name: order-service
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      service: ${spring.application.name}