receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Traces -> Tempo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Logs -> Loki (via OTLP HTTP)
  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  # Metrics -> Prometheus scrape
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]